name: Build and push docker image

on:
  push:
  pull_request:

jobs:
  call-build-and-push-service:
    uses: qlever-llc/workflows/.github/build-and-push-service.yml
    with:
      inputs:
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_repo: ${{ secrets.DOCKERHUB_REPO }}
        snyk_org: ${{ secrets.SNYK_ORG }}
      secrets:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
        snyk_token: ${{ secrets.SNYK_TOKEN }}
